package com.chinamobile.android.connectionmanager.omadm;

/**
 * protocol exception
 *
 */
public class ProtocolException extends CodedException {

    // Protocol codes 

    /** Generic error caused by the client */
    public static final int CLIENT_ERROR      = 400;
    /** Authentication error from remote server */
    public static final int AUTH_ERROR        = 401;
    /** Error accessing a remote resource */
    public static final int ACCESS_ERROR      = 404;
    /** Can not open connection error */
    public static final int CONN_NOT_FOUND    = 406;
    /** Response data null */
    public static final int DATA_NULL         = 407;
    /** Malformed URL error */
    public static final int ILLEGAL_ARGUMENT  = 409;
    /** Remote device (server in sapi sync) full */
    public static final int DEVICE_FULL       = 418;
    /** Local device (client in sapi sync) full */
    public static final int LOCAL_DEVICE_FULL = 419;
    
    /** Generic server error */
    public static final int SERVER_ERROR      = 500;
    /** Server busy: another sync may be in progress */
    public static final int SERVER_BUSY       = 503;
    /** Processing error in the backend connector */
    public static final int BACKEND_ERROR     = 506;
    /** Refresh required by server */
    public static final int REFRESH_REQUIRED  = 508;
    /** Processing error in the backend connector */
    public static final int BACKEND_AUTH_ERROR= 511;
    /** User not authorized */
    public static final int FORBIDDEN_ERROR   = 403;
    /** Source URI not found on server */
    public static final int NOT_FOUND_URI_ERROR = 405;

    //Exception error codes not generated by the protocol
    /** Network problem when reading response from server */
    public static final int READ_SERVER_RESPONSE_ERROR = 0;
    /** Network problem when reading response from server */
    public static final int WRITE_SERVER_REQUEST_ERROR = 1;
    /** Network problem opening connection */
    public static final int SERVER_CONNECTION_REQUEST_ERROR = 2;

    /**User denied permission */
    public static final int CONNECTION_BLOCKED_BY_USER = 3;
    
    /** Server does not support smart slow sync */
    public static final int SMART_SLOW_SYNC_UNSUPPORTED = 4;

    /** The sync got cancelled */
    public static final int CANCELLED = 5;

    /** The sync for the given source is not supported */
    public static final int NOT_SUPPORTED = 6;

    /** The local sd card is not available */
    public static final int SD_CARD_UNAVAILABLE = 7;

    /** Represents a controlled excpetion that will be catched by the user */
    public static final int CONTROLLED_INTERRUPTION = 8;

    /**
     * Constructs an instance of <code>SyncException</code>
     * with the specified detail message.
     *
     * @param code the error code.
     * @param msg the detail message.
     */
    public ProtocolException(int code, String msg) {
        super(code, msg);
    }

}
